---
# tasks file for micro
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
- name: Update apt and install docker-ce-cli
  apt: update_cache=yes name=docker-ce-cli state=latest
- name: Update apt and install containerd.io
  apt: update_cache=yes name=containerd.io state=latest
- name: Update apt and install python-docker
  apt: update_cache=yes name=python-docker state=latest
- name: Install python3-pip
  apt: 
    name: python3-pip
- name: Install docker-py via pip
  pip:
    name: docker-py
- name: Add appuser to docker group
  user:
    name: appuser
    groups: docker
    append: yes
