#image: ruby:2.4.2
image: docker:19.03.1
stages:
  - build
  - test
#  - review
  - deploy
  - stage
  - production
variables:
#  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"  
#before_script:
#  - cd reddit
#  - bundle install
build_job:
  services:
    - name: docker:18.09.7-dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  stage: build
  tags:
    - docker
  before_script:
    - docker info
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
  script:
    - echo 'Docker Building'
    - docker build -t reddit:latest docker-monolith/ .
    - docker tag reddit:latest sfrost1988/otus-reddit:$CI_COMMIT_REF_NAME
    - docker push sfrost1988/otus-reddit:$CI_COMMIT_REF_NAME
#test_unit_job:
#  stage: test
#  services:
#    - mongo:latest
#  script:
#    - ruby simpletest.rb
#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'
deploy_dev_job:
  stage: deploy
  script:
    - echo 'Docker Deploy'
    - docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
    - docker run --name reddit -d -p 9292:9292 sfrost/otus-reddit:$CI_COMMIT_REF_NAME
  environment:
    name: dev
    url: http://34.76.97.97:9292
#branch review:
#  stage: review
#  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
#  environment:
#    name: branch/$CI_COMMIT_REF_NAME
#    url: http://$CI_ENVIRONMENT_SLUG.example.com
#  only:
#    - branches
#  except:
#    - master 
staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
