#image: ruby:2.4.2
image: docker:19.03.1
stages:
  - build
  - test
  - review
  - stage
  - production
variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_DRIVER: overlay2
before_script:
  - cd reddit
build_job:
  #image: docker:18.09.7
  stage: build
  services:
    #- docker:18.09.7-dind
    - docker:19.03.1-dind
  script:
    - docker info
    - docker build -t reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID .
    - docker tag reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID sfrost1988/gitlab-reddit:$CI_PIPELINE_IID
    - docker login -u $DOCKER_LOGIN -p "C6K!5d==ev.$)c]F"
    - docker push sfrost1988/gitlab-reddit:$CI_PIPELINE_IID
    - docker images
test_unit_job:
  image: ruby:2.4.2
  stage: test
  services:
    - mongo:latest
  script:
    - echo "Testing 1"
    - ruby simpletest.rb
test_integration_job:
  stage: test
  script:
    - echo "Testing 2"
deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
branch review:
  #image: docker:18.09.7
  image: docker:19.03
  stage: review
  script:
    - echo "Branch review"
    - docker ps --filter name=gitlab-reddit-gitlab-* --filter status=running -aq | xargs docker stop
    - docker run -d --name gitlab-reddit-$CI_COMMIT_REF_NAME-$CI_PIPELINE_IID --rm -p 9292:9292 sfrost1988/gitlab-reddit:$CI_PIPELINE_IID
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://dev.example.com
staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: stage
    url: https://beta.example.com
production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: production
    url: https://example.com
