image: ruby:2.4.2
stages:
  - build
  - test
  - review
  - stage
  - production
variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'
  DOCKER_DRIVER: overlay2
before_script:
  - export homedir=$(pwd)
build_job:
  image: docker:18.09.7
  stage: build
  services:
    - docker:18.09.7-dind
  script:
    - echo "Building docker"
    - cd $homedir
    - docker login -u $DOCKER_LOGIN -p "C6K!5d==ev.$)c]F"
    - cd docker-monolith
    - docker build -t reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID .
    - docker tag reddit-$CI_COMMIT_REF_NAME:$CI_PIPELINE_IID $DOCKER_LOGIN/gitlab-reddit:3.0
    - docker push $DOCKER_LOGIN/gitlab-reddit:3.0
test_unit_job:
  before_script:
    - export homedir=$(pwd)
    - cd reddit
    - bundle install
  stage: test
  services:
    - mongo:latest
  script:
    - echo "Testing 1"
    - ruby simpletest.rb
test_integration_job:
  stage: test
  script:
    - echo "Testing 2"
deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com
branch review:
  image: docker:18.09.7
  stage: review
  script:
    - echo 'Deploy docker'
    - cd $homedir
    - apk update
    - apk add openssl tar curl docker
    - base=https://github.com/docker/machine/releases/download/v0.14.0 && curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && install /tmp/docker-machine docker-machine
    - ./docker-machine create --driver google --google-project docker-268618 --google-machine-image https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts --google-machine-type n1-standard-1 --google-disk-size "50" --google-tags docker-host --google-zone europe-west1-b "${CI_COMMIT_REF_NAME}-${$CI_PIPELINE_IID}"
    - eval $(./docker-machine env --shell sh ${CI_COMMIT_REF_NAME}-${CI_PIPELINE_IID})
    - docker run -d -p 9292:9292 --name redditapp $DOCKER_LOGIN/gitlab-reddit:3.0
  environment:
    name: dev
    url: http://dev.example.com
staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: stage
    url: https://beta.example.com
production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo "Deploy"
  environment:
    name: production
    url: https://example.com
