version: '3.3'
services:
  post_db:
    image: mongo:${DBVERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UIVERSION}
    environment:      
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - ui_app:/app
    ports: 
      - '${UIextPORT}:${UIintPORT}/tcp'
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:${POSTVERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    volumes:
      - post_app:/app
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENTVERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    volumes:
      - comment_app:/app
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
volumes:
  post_db:
  comment_app:
  post_app:
  ui_app:
networks:
  front_net:
  back_net:
