version: '3.3'
services:
  post_db:
    image: mongo:${DBVERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UIVERSION}
    command: --debug -w 2
    volumes:
      - ui_app:/app
    ports: 
      - '${UIextPORT}:${UIintPORT}/tcp'
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:${POSTVERSION}
    volumes:
      - post_app:/app
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:${COMMENTVERSION}
    volumes:
      - comment_app:/app
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
volumes:
  post_db:
  comment_app:
  post_app:
  ui_app:
networks:
  front_net:
  back_net:
