global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergei_kurbatov'
- name: 'email-me'
  email_configs:
    - to:  deadfroz@gmail.com
      from: alert@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: alert@gmail.com
      auth_identity: alert@gmail.com
      auth_password: 123qweasd
