{
 "title": "UI_Service_Monitoring",
 "time": { "from": "2020-04-25T12:56:03.805Z", "to": "2020-04-25T13:56:03.805Z" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "UI HTTP Request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{kubernetes_namespace=~\"$namespace\",http_status=~\"^[2].*\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{kubernetes_namespace=~\"$namespace\",http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Response time 95th procentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  }
 ]
}