version: '3.3'
services:
  post_db:
    image: mongo:${DBVERSION}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UIVERSION}
    ports: 
      - ${UIextPORT}:${UIintPORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POSTVERSION}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENTVERSION}
    networks:
      - back_net
      - front_net
volumes:
  post_db:
networks:
  front_net:
  back_net:
